// Delivery of signed approval batches from OPS to a block producer (the Besu
// plugin or the Reth node). Semantics, status codes and retries:
// docs/implementation/approvals-wire-contract.md.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.2
// source: ops/approvals/v1/approvals.proto

package approvalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApprovalDelivery_Deliver_FullMethodName = "/ops.approvals.v1.ApprovalDelivery/Deliver"
	ApprovalDelivery_Status_FullMethodName  = "/ops.approvals.v1.ApprovalDelivery/Status"
)

// ApprovalDeliveryClient is the client API for ApprovalDelivery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApprovalDeliveryClient interface {
	// Deliver verifies and stores one signed batch. OK means every approval in
	// the batch is stored; any error means none is. A batch is all or nothing.
	// A full store answers UNAVAILABLE with the trailer
	// "ops-approval-reason: store-full".
	Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error)
	// Status identifies the receiver. OPS calls it after every (re)connect and
	// resends the batches it retains when the boot id has changed.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type approvalDeliveryClient struct {
	cc grpc.ClientConnInterface
}

func NewApprovalDeliveryClient(cc grpc.ClientConnInterface) ApprovalDeliveryClient {
	return &approvalDeliveryClient{cc}
}

func (c *approvalDeliveryClient) Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverResponse)
	err := c.cc.Invoke(ctx, ApprovalDelivery_Deliver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *approvalDeliveryClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, ApprovalDelivery_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApprovalDeliveryServer is the server API for ApprovalDelivery service.
// All implementations must embed UnimplementedApprovalDeliveryServer
// for forward compatibility.
type ApprovalDeliveryServer interface {
	// Deliver verifies and stores one signed batch. OK means every approval in
	// the batch is stored; any error means none is. A batch is all or nothing.
	// A full store answers UNAVAILABLE with the trailer
	// "ops-approval-reason: store-full".
	Deliver(context.Context, *DeliverRequest) (*DeliverResponse, error)
	// Status identifies the receiver. OPS calls it after every (re)connect and
	// resends the batches it retains when the boot id has changed.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedApprovalDeliveryServer()
}

// UnimplementedApprovalDeliveryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApprovalDeliveryServer struct{}

func (UnimplementedApprovalDeliveryServer) Deliver(context.Context, *DeliverRequest) (*DeliverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedApprovalDeliveryServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedApprovalDeliveryServer) mustEmbedUnimplementedApprovalDeliveryServer() {}
func (UnimplementedApprovalDeliveryServer) testEmbeddedByValue()                          {}

// UnsafeApprovalDeliveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApprovalDeliveryServer will
// result in compilation errors.
type UnsafeApprovalDeliveryServer interface {
	mustEmbedUnimplementedApprovalDeliveryServer()
}

func RegisterApprovalDeliveryServer(s grpc.ServiceRegistrar, srv ApprovalDeliveryServer) {
	// If the following call panics, it indicates UnimplementedApprovalDeliveryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApprovalDelivery_ServiceDesc, srv)
}

func _ApprovalDelivery_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalDeliveryServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalDelivery_Deliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalDeliveryServer).Deliver(ctx, req.(*DeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApprovalDelivery_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApprovalDeliveryServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApprovalDelivery_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApprovalDeliveryServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApprovalDelivery_ServiceDesc is the grpc.ServiceDesc for ApprovalDelivery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApprovalDelivery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ops.approvals.v1.ApprovalDelivery",
	HandlerType: (*ApprovalDeliveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deliver",
			Handler:    _ApprovalDelivery_Deliver_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _ApprovalDelivery_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ops/approvals/v1/approvals.proto",
}
