// Delivery of signed approval batches from OPS to a block producer (the Besu
// plugin or the Reth node). Semantics, status codes and retries:
// docs/implementation/approvals-wire-contract.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: ops/approvals/v1/approvals.proto

package approvalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The signed envelope byte for byte: the signed message followed by the
	// 64-byte Ed25519 signature.
	Batch         []byte `protobuf:"bytes,1,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverRequest) Reset() {
	*x = DeliverRequest{}
	mi := &file_ops_approvals_v1_approvals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverRequest) ProtoMessage() {}

func (x *DeliverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_approvals_v1_approvals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverRequest.ProtoReflect.Descriptor instead.
func (*DeliverRequest) Descriptor() ([]byte, []int) {
	return file_ops_approvals_v1_approvals_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverRequest) GetBatch() []byte {
	if x != nil {
		return x.Batch
	}
	return nil
}

type DeliverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Random identifier of the receiver's current process start.
	BootId string `protobuf:"bytes,1,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	// Approvals stored from this batch; equal to the batch size on OK.
	Stored        uint32 `protobuf:"varint,2,opt,name=stored,proto3" json:"stored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverResponse) Reset() {
	*x = DeliverResponse{}
	mi := &file_ops_approvals_v1_approvals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverResponse) ProtoMessage() {}

func (x *DeliverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_approvals_v1_approvals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverResponse.ProtoReflect.Descriptor instead.
func (*DeliverResponse) Descriptor() ([]byte, []int) {
	return file_ops_approvals_v1_approvals_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverResponse) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *DeliverResponse) GetStored() uint32 {
	if x != nil {
		return x.Stored
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_ops_approvals_v1_approvals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ops_approvals_v1_approvals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_ops_approvals_v1_approvals_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	BootId  string                 `protobuf:"bytes,1,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ChainId uint64                 `protobuf:"varint,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Key ids the receiver trusts, so a sender sees a rotation gap before its
	// first batch is refused.
	TrustedKeyIds []string `protobuf:"bytes,3,rep,name=trusted_key_ids,json=trustedKeyIds,proto3" json:"trusted_key_ids,omitempty"`
	// The longest expires_at - issued_at the receiver accepts, in milliseconds.
	MaxTtlMs uint64 `protobuf:"varint,4,opt,name=max_ttl_ms,json=maxTtlMs,proto3" json:"max_ttl_ms,omitempty"`
	// How many approvals the receiver's store holds.
	Capacity uint64 `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// How long a pooled transaction waits for its approval, in milliseconds.
	WaitMs        uint64 `protobuf:"varint,6,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_ops_approvals_v1_approvals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ops_approvals_v1_approvals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_ops_approvals_v1_approvals_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *StatusResponse) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *StatusResponse) GetTrustedKeyIds() []string {
	if x != nil {
		return x.TrustedKeyIds
	}
	return nil
}

func (x *StatusResponse) GetMaxTtlMs() uint64 {
	if x != nil {
		return x.MaxTtlMs
	}
	return 0
}

func (x *StatusResponse) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *StatusResponse) GetWaitMs() uint64 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

var File_ops_approvals_v1_approvals_proto protoreflect.FileDescriptor

const file_ops_approvals_v1_approvals_proto_rawDesc = "" +
	"\n" +
	" ops/approvals/v1/approvals.proto\x12\x10ops.approvals.v1\"&\n" +
	"\x0eDeliverRequest\x12\x14\n" +
	"\x05batch\x18\x01 \x01(\fR\x05batch\"B\n" +
	"\x0fDeliverResponse\x12\x17\n" +
	"\aboot_id\x18\x01 \x01(\tR\x06bootId\x12\x16\n" +
	"\x06stored\x18\x02 \x01(\rR\x06stored\"\x0f\n" +
	"\rStatusRequest\"\xbf\x01\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\aboot_id\x18\x01 \x01(\tR\x06bootId\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\x04R\achainId\x12&\n" +
	"\x0ftrusted_key_ids\x18\x03 \x03(\tR\rtrustedKeyIds\x12\x1c\n" +
	"\n" +
	"max_ttl_ms\x18\x04 \x01(\x04R\bmaxTtlMs\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x04R\bcapacity\x12\x17\n" +
	"\await_ms\x18\x06 \x01(\x04R\x06waitMs2\xaf\x01\n" +
	"\x10ApprovalDelivery\x12N\n" +
	"\aDeliver\x12 .ops.approvals.v1.DeliverRequest\x1a!.ops.approvals.v1.DeliverResponse\x12K\n" +
	"\x06Status\x12\x1f.ops.approvals.v1.StatusRequest\x1a .ops.approvals.v1.StatusResponseBQ\n" +
	"\x12ops.approvals.grpcP\x01Z9privacy-proxy/internal/nodeapproval/approvalpb;approvalpbb\x06proto3"

var (
	file_ops_approvals_v1_approvals_proto_rawDescOnce sync.Once
	file_ops_approvals_v1_approvals_proto_rawDescData []byte
)

func file_ops_approvals_v1_approvals_proto_rawDescGZIP() []byte {
	file_ops_approvals_v1_approvals_proto_rawDescOnce.Do(func() {
		file_ops_approvals_v1_approvals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ops_approvals_v1_approvals_proto_rawDesc), len(file_ops_approvals_v1_approvals_proto_rawDesc)))
	})
	return file_ops_approvals_v1_approvals_proto_rawDescData
}

var file_ops_approvals_v1_approvals_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ops_approvals_v1_approvals_proto_goTypes = []any{
	(*DeliverRequest)(nil),  // 0: ops.approvals.v1.DeliverRequest
	(*DeliverResponse)(nil), // 1: ops.approvals.v1.DeliverResponse
	(*StatusRequest)(nil),   // 2: ops.approvals.v1.StatusRequest
	(*StatusResponse)(nil),  // 3: ops.approvals.v1.StatusResponse
}
var file_ops_approvals_v1_approvals_proto_depIdxs = []int32{
	0, // 0: ops.approvals.v1.ApprovalDelivery.Deliver:input_type -> ops.approvals.v1.DeliverRequest
	2, // 1: ops.approvals.v1.ApprovalDelivery.Status:input_type -> ops.approvals.v1.StatusRequest
	1, // 2: ops.approvals.v1.ApprovalDelivery.Deliver:output_type -> ops.approvals.v1.DeliverResponse
	3, // 3: ops.approvals.v1.ApprovalDelivery.Status:output_type -> ops.approvals.v1.StatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ops_approvals_v1_approvals_proto_init() }
func file_ops_approvals_v1_approvals_proto_init() {
	if File_ops_approvals_v1_approvals_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ops_approvals_v1_approvals_proto_rawDesc), len(file_ops_approvals_v1_approvals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ops_approvals_v1_approvals_proto_goTypes,
		DependencyIndexes: file_ops_approvals_v1_approvals_proto_depIdxs,
		MessageInfos:      file_ops_approvals_v1_approvals_proto_msgTypes,
	}.Build()
	File_ops_approvals_v1_approvals_proto = out.File
	file_ops_approvals_v1_approvals_proto_goTypes = nil
	file_ops_approvals_v1_approvals_proto_depIdxs = nil
}
